## **DATA LOADING AND DATA READING:**

In [1]:
import pandas as pd  
data=pd.read_csv(r'C:\Users\zbook\Documents\AI Project\processes2.csv')
data

,Unnamed: 0,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,max_power (in bph),Mileage Unit,Mileage,Engine (CC)
0,0,Maruti,2014,450000,145500,Diesel,Individual,Manual,First Owner,5,74.00,kmpl,23.40,1248
1,2,Hyundai,2010,225000,127000,Diesel,Individual,Manual,First Owner,5,90.00,kmpl,23.00,1396
2,4,Hyundai,2017,440000,45000,Petrol,Individual,Manual,First Owner,5,81.86,kmpl,20.14,1197
3,7,Toyota,2011,350000,90000,Diesel,Individual,Manual,First Owner,5,67.10,kmpl,23.59,1364
4,8,Ford,2013,200000,169000,Diesel,Individual,Manual,First Owner,5,68.10,kmpl,20.00,1399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,6245,Maruti,2017,425000,12000,Petrol,Individual,Manual,First Owner,5,67.04,kmpl,23.10,998
2091,6246,Toyota,2014,425000,50000,Diesel,Individual,Manual,First Owner,5,67.06,kmpl,23.59,1364
2092,6249,Maruti,2011,200000,73000,Petrol,Individual,Manual,First Owner,5,46.30,kmpl,19.70,796
2093,6253,Maruti,2017,360000,80000,Petrol,Individual,Manual,First Owner,5,67.04,kmpl,20.51,998
2094,6256,Hyundai,2014,475000,80000,Diesel,Individual,Manual,Second Owner,5,88.73,kmpl,22.54,1396

## **DATA EXPLORATION:**

In [2]:
data.head()

,Unnamed: 0,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,max_power (in bph),Mileage Unit,Mileage,Engine (CC)
0,0,Maruti,2014,450000,145500,Diesel,Individual,Manual,First Owner,5,74.00,kmpl,23.40,1248
1,2,Hyundai,2010,225000,127000,Diesel,Individual,Manual,First Owner,5,90.00,kmpl,23.00,1396
2,4,Hyundai,2017,440000,45000,Petrol,Individual,Manual,First Owner,5,81.86,kmpl,20.14,1197
3,7,Toyota,2011,350000,90000,Diesel,Individual,Manual,First Owner,5,67.10,kmpl,23.59,1364
4,8,Ford,2013,200000,169000,Diesel,Individual,Manual,First Owner,5,68.10,kmpl,20.00,1399

In [3]:
data.tail()

,Unnamed: 0,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,max_power (in bph),Mileage Unit,Mileage,Engine (CC)
2090,6245,Maruti,2017,425000,12000,Petrol,Individual,Manual,First Owner,5,67.04,kmpl,23.10,998
2091,6246,Toyota,2014,425000,50000,Diesel,Individual,Manual,First Owner,5,67.06,kmpl,23.59,1364
2092,6249,Maruti,2011,200000,73000,Petrol,Individual,Manual,First Owner,5,46.30,kmpl,19.70,796
2093,6253,Maruti,2017,360000,80000,Petrol,Individual,Manual,First Owner,5,67.04,kmpl,20.51,998
2094,6256,Hyundai,2014,475000,80000,Diesel,Individual,Manual,Second Owner,5,88.73,kmpl,22.54,1396

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2095 entries, 0 to 2094
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          2095 non-null   int64
 1   name                2095 non-null   str
 2   year                2095 non-null   int64
 3   selling_price       2095 non-null   int64
 4   km_driven           2095 non-null   int64
 5   fuel                2095 non-null   str
 6   seller_type         2095 non-null   str
 7   transmission        2095 non-null   str
 8   owner               2095 non-null   str
 9   seats               2095 non-null   int64
 10  max_power (in bph)  2095 non-null   float64
 11  Mileage Unit        2095 non-null   str
 12  Mileage             2095 non-null   float64
 13  Engine (CC)         2095 non-null   int64
dtypes: float64(2), int64(6), str(6)
memory usage: 229.3 KB

In [5]:
print('rows: ', data.shape[0])
print('columns: ', data.shape[1])

rows:  2095
columns:  14

In [6]:
data.isnull().sum()

Unnamed: 0            0
name                  0
year                  0
selling_price         0
km_driven             0
fuel                  0
seller_type           0
transmission          0
owner                 0
seats                 0
max_power (in bph)    0
Mileage Unit          0
Mileage               0
Engine (CC)           0
dtype: int64

In [7]:
Data=data.fillna(data.mean)
Data=data.fillna(data.median)
Data=data.fillna(data.mode())